project:
  synthesize: True
  name: example3
  location: ./tutorials/example/
  inputs:
    entities: [household, person]
    housing_entities: [household]
    person_entities: [person]
    column_names:
      hid: hid
      pid: pid
      geo: geo
      region: region
      sample_geo: sample_geo
    location:
      geo_corr_mapping:
        geo_to_sample: geo_sample_mapping.csv
        region_to_sample: region_sample_mapping.csv
        region_to_geo: region_geo_mapping.csv
      sample:
        household: household_sample.csv
        person: person_sample.csv
      marginals:
        region:
          household: region_household_marginals.csv
          person: region_person_marginals.csv
        geo:
          household: household_marginals.csv
          person: person_marginals.csv
  scenario:
    - description: all_controls_ipu
      apply_region_controls: False
      control_variables:
        region:
          household: []
          person: []
        geo:
          household: [hhldsize]
          person: [gender, age]
      parameters:
        ipf:
          tolerance: 0.0001
          iterations: 250
          zero_marginal_correction: 0.00001
          rounding_procedure: bucket
          archive_performance_frequency: 1
        reweighting:
          procedure: ipu
          tolerance: 0.0001
          inner_iterations: 1
          outer_iterations: 1000
          archive_performance_frequency: 1
        draws:
          pvalue_tolerance: 0.9999
          iterations: 25
          seed: 0
      geos_to_synthesize:
        region:
          ids: [1]
          all_ids: True
        geo:
          ids: []
          all_ids: True
      outputs:
        performance: [ipf, reweighting, drawing]
        weights:
          export: True
          collate_across_geos: True
        multiway:
          - variables: [gender]
            filename: age.csv
            filetype: csv
            entity: person
          - variables: [hhldsize]
            filename: hhldsize.csv
            filetype: csv
            entity: household
        summary:
          region:
            filename: summary_region.csv
            filetype: csv
          geo:
            filename: summary_geo.csv
            filetype: csv
        synthetic_population:
          housing:
            filename: housing_synthetic_Test.csv
            filetype: csv
          person:
            filename: person_synthetic_Test.csv
            filetype: csv
