project:
 name: example
 location: ../demo/example/
 inputs:
  entities: [household, person]
  housing_entities: [household]
  person_entities: [person]
  column_names:
   hid: hid
   pid: pid
   geo: geo
   region: region
   sample_geo: sample_geo
  location:
   geo_corr_mapping:
    geo_to_sample: ../demo/example/geo_sample_mapping.csv
    region_to_sample: ../demo/example/region_sample_mapping.csv
    region_to_geo: ../demo/example/region_geo_mapping.csv
   sample:
    household: ../demo/example/household_sample.csv
    person: ../demo/example/person_sample.csv
   marginals:
    geo:
     household: ../demo/example/household_marginals.csv
     person: ../demo/example/person_marginals.csv
    region:
     household: ../demo/example/region_household_marginals.csv
     person: ../demo/example/region_person_marginals.csv
 scenario:
  - description: derived_2_entropy
    apply_region_controls: True
    control_variables:
     region:
      household: [rhhldtype]
      person: []
     geo:
      household: [hhldtype]
      person: [ptype]
    parameters:
     ipf:
      tolerance: 0.0001
      iterations: 250
      zero_marginal_correction: 0.00001
      rounding_procedure: bucket
      archive_performance_frequency: 1
     reweighting:
      procedure: entropy
      tolerance: 0.0001
      inner_iterations: 1
      outer_iterations: 1000
      archive_performance_frequency: 1
     draws:
      pvalue_tolerance: 0.9999
      iterations: 25
      seed: 0
    geos_to_synthesize:
     region:
      ids: [1]
      all_ids: True
    outputs:
     performance: [ipf, reweighting, drawing]
     weights:
      export: True
      collate_across_geos: False
     multiway:
      - variables: [ptype]
        filename: ptype.csv
        filetype: csv
        entity: person
      - variables: [hhldtype]
        filename: hhldtype.csv
        filetype: csv
        entity: household
      - variables: [rhhldtype]
        filename: rhhldtype.csv
        filetype: csv
        entity: household
     summary:
      region:
       filename: summary_region.csv
       filetype: csv
      geo:
       filename: summary_geo.csv
       filetype: csv
     synthetic_population:
      housing:
       filename: housing_synthetic.csv
       filetype: csv
      person:
       filename: person_synthetic.csv
       filetype: csv
  - description: derived_2_entropy_without_region
    apply_region_controls: True
    control_variables:
     region:
      household: []
      person: []
     geo:
      household: [hhldtype]
      person: [ptype]
    parameters:
     ipf:
      tolerance: 0.0001
      iterations: 250
      zero_marginal_correction: 0.00001
      rounding_procedure: bucket
      archive_performance_frequency: 1
     reweighting:
      procedure: entropy
      tolerance: 0.0001
      inner_iterations: 1
      outer_iterations: 1000
      archive_performance_frequency: 1
     draws:
      pvalue_tolerance: 0.9999
      iterations: 25
      seed: 0
    geos_to_synthesize:
     region:
      ids: [1]
      all_ids: True
    outputs:
     performance: [ipf, reweighting, drawing]
     weights:
      export: True
      collate_across_geos: False
     multiway:
      - variables: [ptype]
        filename: ptype.csv
        filetype: csv
        entity: person
      - variables: [hhldtype]
        filename: hhldtype.csv
        filetype: csv
        entity: household
      - variables: [rhhldtype]
        filename: rhhldtype.csv
        filetype: csv
        entity: household
     summary:
      region:
       filename: summary_region.csv
       filetype: csv
      geo:
       filename: summary_geo.csv
       filetype: csv
     synthetic_population:
      housing:
       filename: housing_synthetic.csv
       filetype: csv
      person:
       filename: person_synthetic.csv
       filetype: csv
  - description: derived_2_ipu
    apply_region_controls: True
    control_variables:
     region:
      household: [rhhldtype]
      person: []
     geo:
      household: [hhldtype]
      person: [ptype]
    parameters:
     ipf:
      tolerance: 0.0001
      iterations: 250
      zero_marginal_correction: 0.00001
      rounding_procedure: bucket
      archive_performance_frequency: 1
     reweighting:
      procedure: ipu
      tolerance: 0.0001
      inner_iterations: 1
      outer_iterations: 1000
      archive_performance_frequency: 1
     draws:
      pvalue_tolerance: 0.9999
      iterations: 25
      seed: 0
    geos_to_synthesize:
     region:
      ids: [1]
      all_ids: True
    outputs:
     performance: [ipf, reweighting, drawing]
     weights:
      export: True
      collate_across_geos: False
     multiway:
      - variables: [ptype]
        filename: ptype.csv
        filetype: csv
        entity: person
      - variables: [hhldtype]
        filename: hhldtype.csv
        filetype: csv
        entity: household
      - variables: [rhhldtype]
        filename: rhhldtype.csv
        filetype: csv
        entity: household
     summary:
      region:
       filename: summary_region.csv
       filetype: csv
      geo:
       filename: summary_geo.csv
       filetype: csv
     synthetic_population:
      housing:
       filename: housing_synthetic.csv
       filetype: csv
      person:
       filename: person_synthetic.csv
       filetype: csv
  - description: derived_2_ipu_without_region
    apply_region_controls: True
    control_variables:
     region:
      household: []
      person: []
     geo:
      household: [hhldtype]
      person: [ptype]
    parameters:
     ipf:
      tolerance: 0.0001
      iterations: 250
      zero_marginal_correction: 0.00001
      rounding_procedure: bucket
      archive_performance_frequency: 1
     reweighting:
      procedure: ipu
      tolerance: 0.0001
      inner_iterations: 1
      outer_iterations: 1000
      archive_performance_frequency: 1
     draws:
      pvalue_tolerance: 0.9999
      iterations: 25
      seed: 0
    geos_to_synthesize:
     region:
      ids: [1]
      all_ids: True
    outputs:
     performance: [ipf, reweighting, drawing]
     weights:
      export: True
      collate_across_geos: False
     multiway:
      - variables: [ptype]
        filename: ptype.csv
        filetype: csv
        entity: person
      - variables: [hhldtype]
        filename: hhldtype.csv
        filetype: csv
        entity: household
      - variables: [rhhldtype]
        filename: rhhldtype.csv
        filetype: csv
        entity: household
     summary:
      region:
       filename: summary_region.csv
       filetype: csv
      geo:
       filename: summary_geo.csv
       filetype: csv
     synthetic_population:
      housing:
       filename: housing_synthetic.csv
       filetype: csv
      person:
       filename: person_synthetic.csv
       filetype: csv
